### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by mariumtapal** [baumer-lab/fec20#6]
- [ ] vignette
- [ ] NEWS.md
- [ ] cran-comments.md
- [ ] update version number
- [ ] test with rhub and other platforms
